#!/usr/bin/env bash
set -euo pipefail
OUT="$(/usr/bin/seasoning which-output 2>/dev/null || echo default)"
F="$HOME/.cache/seasoning/$OUT/side.right.mode"; M=0; [[ -f "$F" ]] && M=$(<"$F")
case "$M" in
  0) date +'%B %Y' ;;
  1) date +'%d %B' ;;
  2) date +'W%V %Y' ;;
  3) date +'%Y-%m-%d' ;;
esac
